export const BRAND = '#8B3A3A'
export const BRAND_DARK = '#5C1A1A'
export const BRAND_LIGHT = '#f5d0d0'

export const COLORS = {
  brand: BRAND,
  brandDark: BRAND_DARK,
  brandLight: BRAND_LIGHT,
  success: '#059669',
  warning: '#D97706',
  danger: '#DC2626',
  info: '#2563EB',
  purple: '#7C3AED',
  gray50: '#F9FAFB',
  gray100: '#F3F4F6',
  gray200: '#E5E7EB',
  gray400: '#9CA3AF',
  gray500: '#6B7280',
  gray600: '#4B5563',
  gray700: '#374151',
  gray900: '#111827',
  white: '#FFFFFF',
}

export const STATUS_COLORS: Record<string, string> = {
  RFQ_DRAFT: '#6B7280',
  RFQ_OPEN: '#2563EB',
  SUPPLIER_QUOTES_REQUESTED: '#D97706',
  SUPPLIER_QUOTES_RECEIVED: '#D97706',
  PRICING_IN_PROGRESS: '#7C3AED',
  INTERNAL_REVIEW_PENDING: '#D97706',
  APPROVED_FOR_CLIENT: '#059669',
  SENT_TO_CLIENT: '#2563EB',
  CLIENT_ACCEPTED: '#059669',
  PO_RECEIVED: '#059669',
  SUPPLIER_SELECTED: '#059669',
  PRO_FORMA_RECEIVED: '#059669',
  REQUISITION_APPROVED: '#059669',
  PAID_TO_SUPPLIER: '#059669',
  DELIVERY_CONFIRMED: '#059669',
  INVOICE_ISSUED: '#2563EB',
  INVOICE_PAID: '#059669',
  CLOSED: '#059669',
  LOST: '#DC2626',
  CANCELLED: '#DC2626',
  PENDING: '#D97706',
  APPROVED: '#059669',
  REJECTED: '#DC2626',
  DRAFT: '#6B7280',
  ISSUED: '#2563EB',
  PAID: '#059669',
  OVERDUE: '#DC2626',
}

export const STATUS_LABELS: Record<string, string> = {
  RFQ_DRAFT: 'Draft',
  RFQ_OPEN: 'Open',
  SUPPLIER_QUOTES_REQUESTED: 'Quotes Requested',
  SUPPLIER_QUOTES_RECEIVED: 'Quotes Received',
  PRICING_IN_PROGRESS: 'Pricing',
  INTERNAL_REVIEW_PENDING: 'Pending Review',
  APPROVED_FOR_CLIENT: 'Approved',
  SENT_TO_CLIENT: 'Sent to Client',
  CLIENT_ACCEPTED: 'Accepted',
  PO_RECEIVED: 'PO Received',
  SUPPLIER_SELECTED: 'Supplier Selected',
  PRO_FORMA_RECEIVED: 'Pro Forma Received',
  REQUISITION_PENDING: 'Requisition Pending',
  REQUISITION_APPROVED: 'Requisition Approved',
  PAYMENT_PENDING: 'Payment Pending',
  PAID_TO_SUPPLIER: 'Paid',
  DELIVERY_SCHEDULED: 'Delivery Scheduled',
  IN_TRANSIT: 'In Transit',
  DELIVERED: 'Delivered',
  DELIVERY_CONFIRMED: 'Delivery Confirmed',
  INVOICE_DRAFT: 'Invoice Draft',
  INVOICE_ISSUED: 'Invoiced',
  INVOICE_PAID: 'Invoice Paid',
  CLOSED: 'Closed',
  LOST: 'Lost',
  CANCELLED: 'Cancelled',
}
